[workflow]
sequencing_type = 'genome'

first_stages = []
last_stages = []
skip_stages = []
only_stages = [
    'RunVntyper',
]

[vntyper]
# Logs are very slim when set to INFO
log_level = "DEBUG"
# gs:// path to configs that override the VNtyper / kestrel defaults
vntyper_config_json_path = false
kestrel_config_json_path = false

[images]
vntyper = "australia-southeast1-docker.pkg.dev/cpg-common/images/vntyper:2.0.3-2"
