"""The cohort manifest - which datasets a calibration was derived from.

Generated by ``qc_calibrate discover`` but intended to be hand-edited: dropping a
cohort, pinning an older analysis, or substituting a local file are all normal. Because
it is a durable artifact rather than a live query, a calibration stays reproducible
after Metamist moves on.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from align_genotype.qc_calibration import tomlio

_COHORT_KEYS = {'uri', 'analysis_id', 'timestamp'}


class ManifestError(ValueError):
    """The manifest is missing something or is malformed."""


@dataclass(frozen=True)
class Cohort:
    """One dataset's MultiQC report. `uri` is anything cpg_utils.to_path accepts."""

    label: str
    uri: str
    analysis_id: int | None = None
    timestamp: str | None = None


@dataclass(frozen=True)
class Manifest:
    seq_type: str
    generated: str
    cohorts: tuple[Cohort, ...]

    @property
    def labels(self) -> tuple[str, ...]:
        return tuple(c.label for c in self.cohorts)

    def cohort(self, label: str) -> Cohort:
        for c in self.cohorts:
            if c.label == label:
                return c
        raise KeyError(f'{label!r} is not in this manifest; known cohorts: {list(self.labels)}')


def _parse_cohort(label: str, raw: Any) -> Cohort:
    try:
        tomlio.require_bare_key(label, 'cohort label')
    except ValueError as exc:
        raise ManifestError(str(exc)) from exc
    if not isinstance(raw, dict):
        raise ManifestError(f'cohort {label!r}: [cohorts.{label}] must be a table')
    if unknown := sorted(set(raw) - _COHORT_KEYS):
        raise ManifestError(f'cohort {label!r}: unknown key(s) {unknown}; expected {sorted(_COHORT_KEYS)}')
    if 'uri' not in raw:
        raise ManifestError(f'cohort {label!r}: missing required key: uri')
    uri = str(raw['uri'])
    if not uri:
        raise ManifestError(f'cohort {label!r}: uri must not be empty')
    return Cohort(
        label=label,
        uri=uri,
        analysis_id=_optional_int(label, 'analysis_id', raw.get('analysis_id')),
        timestamp=_optional_str(raw.get('timestamp')),
    )


def _optional_int(label: str, field: str, value: Any) -> int | None:
    """Coerce an optional integer, reporting a bad value as a ManifestError.

    A bare ``int()`` would raise ValueError, which the CLI's ``except ManifestError``
    would miss - so the operator would get a traceback instead of a clear message.
    """
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int):
        raise ManifestError(f'cohort {label!r}: {field} must be an integer, got {value!r}')
    return value


def _optional_str(value: Any) -> str | None:
    return None if value is None else str(value)


def loads(text: str) -> Manifest:
    """Parse a manifest from a TOML string."""
    return _from_dict(tomlio.loads(text))


def load(path: str | Path) -> Manifest:
    """Load a manifest from a local or cloud path."""
    return _from_dict(tomlio.load_path(path))


def _from_dict(raw: dict[str, Any]) -> Manifest:
    if 'seq_type' not in raw:
        raise ManifestError('manifest: missing required key: seq_type')
    cohorts_raw = raw.get('cohorts', {})
    if not cohorts_raw:
        raise ManifestError('manifest lists no cohorts; add at least one [cohorts.<LABEL>] table')
    return Manifest(
        seq_type=str(raw['seq_type']),
        generated=str(raw.get('generated', '')),
        cohorts=tuple(_parse_cohort(label, value) for label, value in cohorts_raw.items()),
    )


def dumps(manifest: Manifest) -> str:
    """Render a manifest back to TOML, preserving cohort order."""
    lines = [tomlio.fmt_kv('seq_type', manifest.seq_type), tomlio.fmt_kv('generated', manifest.generated)]
    for cohort in manifest.cohorts:
        # Labels are written unquoted, so reject anything that wouldn't round-trip.
        tomlio.require_bare_key(cohort.label, 'cohort label')
        lines += ['', f'[cohorts.{cohort.label}]', tomlio.fmt_kv('uri', cohort.uri)]
        if cohort.analysis_id is not None:
            lines.append(tomlio.fmt_kv('analysis_id', cohort.analysis_id))
        if cohort.timestamp is not None:
            lines.append(tomlio.fmt_kv('timestamp', cohort.timestamp))
    return '\n'.join(lines) + '\n'


def save(manifest: Manifest, path: str | Path) -> None:
    """Write a manifest to disk."""
    Path(path).write_text(dumps(manifest))
